# 测试环境消息队列配置
# 测试环境使用内存适配器，确保测试的独立性和速度

# 基础配置
adapter: memory # 测试环境使用内存适配器
keyPrefix: "test:messaging:"
enableTenantIsolation: false # 测试环境禁用租户隔离
documentationUrl: "http://localhost:3000/docs/messaging/errors"

# 监控配置 - 测试环境禁用监控
monitoring:
  enableStats: false # 测试环境禁用统计
  enableHealthCheck: false # 测试环境禁用健康检查
  statsInterval: 60000

# 缓存配置 - 测试环境最小化缓存
cache:
  enableMessageDeduplication: false # 测试环境禁用消息去重
  enableConsumerStateCache: false # 测试环境禁用消费者状态缓存
  enableStatsCache: false # 测试环境禁用统计缓存
  enableDeadLetterCache: false # 测试环境禁用死信缓存
  enableTenantConfigCache: false # 测试环境禁用租户配置缓存
  keyPrefix: "test:messaging:cache:"
  cacheTTL:
    messageDedup: 10 # 测试环境使用极短的TTL
    consumerState: 30
    stats: 5
    deadLetter: 60
    tenantConfig: 30

# 多租户配置 - 测试环境禁用
multiTenancy:
  context:
    enableAutoInjection: false # 测试环境禁用自动注入
    contextTimeout: 5000 # 极短的超时时间
    enableAuditLog: false # 测试环境禁用审计日志
    contextStorage: "memory"
    allowCrossTenantAccess: true # 测试环境允许跨租户访问
  isolation:
    strategy: "key-prefix"
    keyPrefix: "test:messaging:"
    namespace: "test-messaging"
    enableIsolation: false # 测试环境禁用隔离
    level: "loose" # 最宽松的隔离级别
  middleware:
    enableTenantMiddleware: false # 测试环境禁用租户中间件
    tenantHeader: "X-Tenant-ID"
    tenantQueryParam: "tenant"
    tenantSubdomain: false # 测试环境禁用子域名支持
    validationTimeout: 100 # 极短的验证超时
    strictValidation: false # 测试环境禁用严格验证
  security:
    enableSecurityCheck: false # 测试环境禁用安全检查
    maxFailedAttempts: 100 # 测试环境允许大量失败尝试
    lockoutDuration: 1000 # 极短的锁定时间
    enableAuditLog: false # 测试环境禁用安全审计
    enableIpWhitelist: false

# 重试配置 - 测试环境最小化重试
retry:
  maxRetries: 0 # 测试环境禁用重试
  retryDelay: 100 # 极短的重试延迟
  backoff: "fixed" # 固定延迟策略
  enableDeadLetterQueue: false # 测试环境禁用死信队列

# 租户配置 - 测试环境简化
tenant:
  enableIsolation: false # 测试环境禁用租户隔离
  tenantPrefix: "test:tenant:"
  autoCreateTenantQueues: false # 测试环境禁用自动创建
  tenantQueueLimit: 5 # 极少的队列限制
