packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - argon2
  - core-js-pure
  - prisma
  - sharp
  - unrs-resolver
